### ISSUE TITLE
"tensor_root": '/data/wangpuyi_data/mplug_tensor/AIGCQA_30k'

### ISSUE THREAD

**Issue by ctxya1207** [wangpuyi/MA-AGIQA#1]
how to gain this root

**Comment by wangpuyi** [comment]
It is said clearly in [Semantic Feature Extraction](https://github.com/wangpuyi/MA-AGIQA?tab=readme-ov-file#semantic-feature-extraction). Please follow the guidance.

**Comment by ctxya1207** [comment]
thank you.May I ask how the file AGIQA_3k.json was made?

**Comment by wangpuyi** [comment]
The json files are converted from csv files, starting from line 56 in [getFeature.py](https://github.com/wangpuyi/MA-AGIQA/blob/main/q_align/getFeature.py). By the way, the csv files is obtained from the original datasets or converted from the original datasets without any change except for the format.

**Comment by ctxya1207** [comment]
Whether the mPLUG-Owl2 model is fine-tuned on Q-align
